<?php
header('Content-type: text/html; charset=utf-8');

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>美装艳遇老虎机 - 拖拉网</title>
<link href="<?php echo APP_SINA_URL;?>src/css/main.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo APP_SINA_URL;?>src/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="<?php echo APP_SINA_URL;?>src/js/jquery.maxlength.js"></script>
<script type="text/javascript" charset="utf-8"    src="http://fusion.qq.com/fusion_loader?appid=<?php echo APP_ID;?>&platform=qzone">
<!--[if IE 6]>
<script type="text/javascript" src="<?php echo APP_SINA_URL;?>src/js/DD_belatedPNG_0.0.8a.js"></script>
<script type="text/javascript">DD_belatedPNG.fix('.pngFix');</script>
<![endif]-->
<script type="text/javascript">
$(document).ready(function(){
	$('textarea.limited').maxlength({
        'feedback' : '#charsLeft', 
		'useInput' : true
    });
});
</script>
</head>
<body>
<?php
//验证用户是否有效
if($_SESSION['userinfo']=="" || $_SESSION['userinfo']==null):?>
<script>
	fusion2.dialog.relogin();
</script>
<?php endif;?>

<div id="cityBg" class="cbody">
<div id="wappper" class="cbody pngFix">
	<div id="wrap" class="clearfix">
    	<h2 class="titH2B"><span class="sina pngFix">发到新浪微博</span></h2>
		<?php /*
    	<div class="clear bImg pngFix" style="margin:0 auto;"><a href="<?php echo APP_DOMAIN.'px/detail.php?id='.$this->data['pxid'];?>" target="_blank"><img src="<?php echo APP_DOMAIN.$this->data['pximg'];?>" width="264" height="264" /></a></div>
		*/?>
    	<div class="clear bImg pngFix" style="margin:0 auto;"><a target="_blank"><img id='J_pic' src="<?php echo APP_DOMAIN.$this->data['pximg'];?>" width="264" height="264" /></a></div>
        <div id="fbwb" class="clearfix">
        	<form action="<?php echo APP_qzone_URL;?>last.php" method="post" name="fbForm" id="fbForm">
        	<?php
        	//统计字数
        	$str = preg_replace('/[\x80-\xff]{1,3}/', ' ', $this->data['pyu'],-1,$n);
			$n 	+= str_word_count($str);
			$leftNum = intval(140 - $n);
        	?>
        	<h2>你还可以输入<em id="charsLeft"><?php echo $leftNum;?></em>字</h2>
            <textarea class="pngFix limited J_content" name="pyu" id="pyu"><?php echo $this->data['pyu'];?></textarea>
            <input type="hidden" name="maxlength" value="140" />
            <input type="hidden" name="appid" value="<?php echo $this->data['id'];?>" />
            <input type="hidden" name="wbauth" value="<?php echo $this->auth;?>" />
            <p class="next-conp" >
            	<span><input type="checkbox" name="totuolar" checked="checked" />同时发布到拖拉网Tuolar<br /><span class="attention" >关注拖拉网官方微博  </span>
        	<iframe src="http://open.qzone.qq.com/like?url=http%3A%2F%2Fuser.qzone.qq.com%2F622001561&type=button_num&width=400&height=30&style=2" allowtransparency="true" scrolling="no" border="0" frameborder="0" style="width:135px;height:24px;border:none;overflow:hidden;float: left;"></iframe></span>
                <a href="javascript:void(0);" id="J_send" class="pngFix" style="margin-left:125px;">发布</a>
            </p>
            </form>
        </div>
        
    </div>
    <!--footer-->
    <div id="footer">
        <h1>拖拉网</h1>
        <p>拖拉网是一个China最领先时尚导购网站，时尚达人随时自主同步世界潮流，<br />收录电商服装，搭配个性的新鲜时尚行头。<br />拖！我最爱  www.tuolar.com</p>
    </div><!--end/footer-->
</div>
</div>
<style>
#fbwb p.next-conp{
	 	margin-top: 3px;
	 	padding:5px 0px 5px 0px;
	 	height:55px;
}
.attention{
	border:0px;
	margin:0px 0px 0px 20px;
	line-height: 24px;
	height: 24px;
	display: block;
	float: left;
	width: 140px;
}


        	</style>

</body>
<script>
$(function(){
	$("#J_send").click(function(){

		fusion2.dialog.tweet
		({
		  // 必须。默认显示在说说文字输入框中的文字内容。
		  msg:$(".J_content").text(),

		  // 可选。应用自定义参数，用于进入应用时CanvasUrl中的app_custom参数的值,应用可根据该参数判断用户来源。
		  source:"adtag_tweet_share_exp",

		  // 可选。要发表带贴图的说说时，这里需要传入图片的链接。链接中请不要带中文字符
		   // 图片没有域名限制，但是图片地址的根域名必须要有一个crossdomain.xml 的flash授权文件，详见下文
		  url:$("#J_pic").attr("src"),

		  // 可选。用户操作后的回调方法。
		  onSuccess : function (opt) {  },

		  // 可选。用户取消操作后的回调方法。
		  onCancel : function () {  },

		  // 可选。对话框关闭时的回调方法。
		  onClose : function () {  }

		});

		$("#fbForm").submit();
				
		});
});


</script>
</html>